apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  storageClassName: local
  accessModes:
    - ReadWriteOnce
